### ISSUE TITLE
Inclusion of http(s):// can create an empty link.

### ISSUE THREAD

**Issue by OhNoYouSquidnt** [justinpotts/pattr#27]
Steps to reproduce:
1. Join a chat
2. Type either "http://" or "https://" only, or with a space after ("https:// so this is a bug?").

Actual result:
You are given a link that leads to either "http:///" or "https:///"

Expected result:
It does not return a link.

![screen shot 2015-11-24 at 12 26 59 pm](https://cloud.githubusercontent.com/assets/14777838/11376513/bb2b85dc-92a6-11e5-98bb-563391ee70fd.png)

**Comment by justinpotts** [comment]
Fixed in e1a8fd39cca7c5f39b3d03f412303ecb76e3552a
