### ISSUE TITLE
Titles name of Chat + unread messages

### ISSUE THREAD

**Issue by champfish** [justinpotts/pattr#7]
The title could be the name of the chat + # of unread messages. For Example "CompSci (3)"

**Comment by jeffw16** [comment]
If you really want this feature, here's how to implement it:
- [ ] Add functionality to see how many messages unread
- [ ] Add message/notification APIs of Chrome/Firefox somehow
- [ ] Implement dynamic title through vanilla JS (https://stackoverflow.com/questions/413439/how-to-dynamically-change-a-web-pages-title)

**Comment by justinpotts** [comment]
Done, done, and done in 1e0edebef9ae52b0c0cd802076c95888df54ce14!
